import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import path from 'path';
import {fileURLToPath} from 'url';
import {createClient} from '@supabase/supabase-js';
const app=express(),PORT=process.env.PORT||10000,__filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename),dist=path.resolve(__dirname,'../../client/dist');
app.use(cors());app.use(express.json());
const hasDB=!!(process.env.SUPABASE_URL&&process.env.SUPABASE_ANON_KEY);const sb=hasDB?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_ANON_KEY):null;
const districts=[['gwarinpa','Gwarinpa',500,'Residential hustle'],['wuse','Wuse',700,'Shopping, offices and city energy'],['wuse2','Wuse 2',900,'Restaurants and nightlife'],['jabi','Jabi',800,'Leisure, food and Jabi Lake'],['garki','Garki',650,'Commercial Abuja'],['maitama','Maitama',1200,'Premium Abuja'],['asokoro','Asokoro',1100,'Quiet and premium'],['central','Central Area',750,'Business and government']].map(([id,name,transport,vibe])=>({id,name,transport,vibe}));
const jobs=[['Job Seeker',0,0,0],['Sales Assistant',85000,22,2],['Customer Support Rep',120000,25,3],['Graphic Designer',170000,25,4],['Junior Developer',240000,28,5],['Data Analyst',300000,28,6],['Banking Analyst',350000,30,7],['Product Manager',500000,32,9]].map(([title,salary,energy,rep])=>({title,salary,energy,rep}));
const housing=[['Shared Apartment',0,2],['Standard Apartment',120000,8],['Wuse Apartment',220000,12],['Maitama Apartment',450000,20],['Luxury Residence',900000,30]].map(([name,cost,happiness])=>({name,cost,happiness}));
const clamp=n=>Math.max(0,Math.min(100,Math.round(n)));
const user=async req=>{if(!sb)return null;const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const {data}=await sb.auth.getUser(h.slice(7));return data.user||null};
async function auth(req,res,next){req.user=await user(req);if(!req.user)return res.status(401).json({error:'Authentication required'});next()}
app.get('/api/health',(req,res)=>res.json({ok:true,app:'AbujaSoftlifeNG',supabase:hasDB}));
app.get('/api/game-data',(req,res)=>res.json({districts,jobs,housing}));
app.get('/api/me',auth,async(req,res)=>{const {data:player,error}=await sb.from('players').select('*').eq('id',req.user.id).maybeSingle();if(error)return res.status(500).json({error:error.message});const {data:activity}=await sb.from('activity_log').select('*').eq('player_id',req.user.id).order('created_at',{ascending:false}).limit(30);res.json({player,activity:activity||[]})});
app.post('/api/player',auth,async(req,res)=>{const p={id:req.user.id,display_name:String(req.body.displayName||'Player').slice(0,30),age:Number(req.body.age)||21,gender:req.body.gender||'Other',district:districts.some(x=>x.id===req.body.district)?req.body.district:'gwarinpa',money:50000,bank_balance:0,health:100,happiness:70,energy:100,reputation:10,job:'Job Seeker',job_salary:0,housing:'Shared Apartment',housing_cost:0};const {data,error}=await sb.from('players').upsert(p).select().single();if(error)return res.status(400).json({error:error.message});await sb.from('activity_log').insert({player_id:req.user.id,action:'Started life',details:'Entered Abuja and began a new story.'});res.json({player:data})});
async function act(req,res,updates,action,amount=0,details=''){const {data,error}=await sb.from('players').update(updates).eq('id',req.user.id).select().single();if(error)return res.status(400).json({error:error.message});await sb.from('activity_log').insert({player_id:req.user.id,action,amount,details});res.json({player:data})}
app.post('/api/action',auth,async(req,res)=>{const {data:p,error}=await sb.from('players').select('*').eq('id',req.user.id).single();if(error||!p)return res.status(404).json({error:'Create your character first'});const {type,value}=req.body;
if(type==='rest')return act(req,res,{energy:clamp(p.energy+45),health:clamp(p.health+3),happiness:clamp(p.happiness+3)},'Rested',0,'Recovered energy.');
if(type==='social'){if(p.energy<10)return res.status(400).json({error:'You need more energy'});return act(req,res,{energy:clamp(p.energy-10),happiness:clamp(p.happiness+12),reputation:clamp(p.reputation+3)},'Went social',0,'Met people and built reputation.');}
if(type==='eat'){let c=3500;if(p.money<c)return res.status(400).json({error:'Not enough cash'});return act(req,res,{money:Number(p.money)-c,energy:clamp(p.energy+18),health:clamp(p.health+4),happiness:clamp(p.happiness+5)},'Ate out',-c,'Food and soft life.');}
if(type==='work'){let j=jobs.find(x=>x.title===p.job);if(!j||!j.salary)return res.status(400).json({error:'Choose a job first'});if(p.energy<j.energy)return res.status(400).json({error:'Too tired. Rest first'});let pay=Math.round(j.salary/22);return act(req,res,{money:Number(p.money)+pay,energy:clamp(p.energy-j.energy),happiness:clamp(p.happiness-3),reputation:clamp(p.reputation+j.rep)},'Worked a shift',pay,`Worked as ${p.job}.`)}
if(type==='travel'){let d=districts.find(x=>x.id===value);if(!d)return res.status(400).json({error:'Unknown district'});if(d.id===p.district)return res.status(400).json({error:'You are already here'});if(p.money<d.transport)return res.status(400).json({error:'Not enough cash for transport'});return act(req,res,{district:d.id,money:Number(p.money)-d.transport,energy:clamp(p.energy-5)},'Travelled',-d.transport,`Travelled to ${d.name}.`)}
if(type==='job'){let j=jobs.find(x=>x.title===value);let reqRep=Math.max(0,jobs.findIndex(x=>x.title===value)*5);if(!j)return res.status(400).json({error:'Unknown job'});if(p.reputation<reqRep)return res.status(400).json({error:`You need ${reqRep} reputation`});return act(req,res,{job:j.title,job_salary:j.salary,happiness:clamp(p.happiness+3),reputation:clamp(p.reputation+2)},'Got a new job',0,`${j.title} — ₦${j.salary.toLocaleString()}/month.`)}
if(type==='housing'){let h=housing.find(x=>x.name===value);if(!h)return res.status(400).json({error:'Unknown housing'});if(p.money<h.cost)return res.status(400).json({error:'You cannot afford this housing yet'});return act(req,res,{money:Number(p.money)-h.cost,housing:h.name,housing_cost:h.cost,happiness:clamp(p.happiness+h.happiness)},'Upgraded housing',-h.cost,`Moved into ${h.name}.`)}
res.status(400).json({error:'Unknown action'})});
app.get('/api/activity',auth,async(req,res)=>{const {data,error}=await sb.from('activity_log').select('*').eq('player_id',req.user.id).order('created_at',{ascending:false}).limit(30);if(error)return res.status(500).json({error:error.message});res.json({activity:data||[]})});
if(process.env.NODE_ENV==='production'){app.use(express.static(dist));app.get('*',(req,res)=>req.path.startsWith('/api/')?res.status(404).json({error:'Not found'}):res.sendFile(path.join(dist,'index.html')))}
app.listen(PORT,()=>console.log('AbujaSoftlifeNG listening on '+PORT));
